/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NlAmbulanceWlList {
    }
}
declare global {
    interface HTMLNlAmbulanceWlListElement extends Components.NlAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLNlAmbulanceWlListElement: {
        prototype: HTMLNlAmbulanceWlListElement;
        new (): HTMLNlAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "nl-ambulance-wl-list": HTMLNlAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface NlAmbulanceWlList {
    }
    interface IntrinsicElements {
        "nl-ambulance-wl-list": NlAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nl-ambulance-wl-list": LocalJSX.IntrinsicElements["nl-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLNlAmbulanceWlListElement>;
        }
    }
}
